# Generated by Django 4.1.5 on 2023-02-16 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "playground",
            "0002_rename_absence_of_any_risk_factor_for_acute_kidney_injury_0_no_1_yes_field_dkadata_absence_of_any_ri",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="dkadata",
            name="Absence_Of_Any_Risk_Factor_For_Acute_Kidney_Injury",
            field=models.CharField(
                choices=[(0, "No"), (1, "Yes")],
                db_column="Absence of Any Risk Factor for Acute Kidney Injury (0 = no, 1 = yes)",
                default="No",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="dkadata",
            name="Acute_Kidney_Injury_In_Hospital",
            field=models.CharField(
                choices=[(0, "No"), (1, "Yes")],
                db_column="Acute Kidney Injury In Hospital (0 = no, 1 yes)",
                default="No",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="dkadata",
            name="Acute_Kidney_Injury_On_Admission",
            field=models.CharField(
                choices=[(0, "No"), (1, "Yes")],
                db_column="Acute Kidney Injury on Admission (0 = no, 1 yes)",
                default="No",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="dkadata",
            name="Contrast_Media_Adminsitered",
            field=models.CharField(
                choices=[(0, "No"), (1, "Yes")],
                db_column="Contrast Media Adminsitered (0 = no, 1 = yes)",
                default="No",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="dkadata",
            name="Diabetes_Type",
            field=models.CharField(
                choices=[(0, "Type 1"), (1, "Type 2")],
                db_column="Diabetes Type (type 1 = 0, type 2 = 1)",
                default="Type 1",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="dkadata",
            name="Gender",
            field=models.CharField(
                choices=[(0, "Male"), (1, "Female")],
                db_column="Gender (0 = male, 1 = female)",
                default="Male",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="dkadata",
            name="Hypotension",
            field=models.CharField(
                choices=[(0, "No"), (1, "Yes")],
                db_column="Hypotension (0 = no, 1 = yes)",
                default="No",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="dkadata",
            name="Inappropriate_Bicarbonate_Use",
            field=models.CharField(
                choices=[(0, "No"), (1, "Yes")],
                db_column="Inappropriate Bicarbonate Use (0 = no, 1 = yes)",
                default="No",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="dkadata",
            name="Infection_As_Cause_Of_DKA",
            field=models.CharField(
                choices=[(0, "No"), (1, "Yes")],
                db_column="Infection as Cause of DKA (0 = no, 1 = yes)",
                default="No",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="dkadata",
            name="Medical_Unit",
            field=models.CharField(
                choices=[(0, "Medical ICU"), (1, "Intermediate Care")],
                db_column="Unit (0 = Medical ICU, 1 = Intermediate Care)",
                default="Medical ICU",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="dkadata",
            name="NSAID_Administration",
            field=models.CharField(
                choices=[(0, "No"), (1, "Yes")],
                db_column="NSAID Administration (0 = no, 1 = yes)",
                default="No",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="dkadata",
            name="New_Onset_Diabetes",
            field=models.CharField(
                choices=[(0, "No"), (1, "Yes")],
                db_column="New Onset Diabetes (0 = no, 1 = yes)",
                default="No",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="dkadata",
            name="Non_Anion_Gap_Acidosis",
            field=models.CharField(
                choices=[(0, "No"), (1, "Yes")],
                db_column="Non-anion Gap Acidosis (0 = no, 1 = yes) ",
                default="No",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="dkadata",
            name="Noncompliance_To_Insulin_At_Home",
            field=models.CharField(
                choices=[(0, "No"), (1, "Yes")],
                db_column="Noncompliance to Insulin at Home (0 = no, 1 = yes)",
                default="No",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="dkadata",
            name="Other_Cause_Of_DKA",
            field=models.CharField(
                choices=[(0, "No"), (1, "Yes")],
                db_column="Other Cause of DKA (0 = no, 1 = yes)",
                default="No",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="dkadata",
            name="Peak_Chloride_Category",
            field=models.CharField(
                choices=[(0, "Normochloremia"), (1, "Hyperchloremia")],
                db_column="Peak Chloride Category (0 = normochloremia, 1 = hyperchloremia)",
                default="Normochloremia",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="dkadata",
            name="Sepsis",
            field=models.CharField(
                choices=[(0, "No"), (1, "Yes")],
                db_column="Sepsis (0 = no, 1 = yes)",
                default="No",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="dkadata",
            name="Serum_Potassium_Maintenane_Within_Normal_Range",
            field=models.CharField(
                choices=[(0, "No"), (1, "Yes")],
                db_column="Serum Potassium Maintenane Within Normal Range (0 = no, 1 = yes)",
                default="No",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="dkadata",
            name="Subcutaneous_Insulin_Overlap_By_1_To_2_Hours",
            field=models.CharField(
                choices=[(0, "No"), (1, "Yes")],
                db_column="Subcutaneous Insulin Overlap by 1-2 hr (0 = no, 1 = yes)",
                default="No",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="dkadata",
            name="Vancomycin_Aministration",
            field=models.CharField(
                choices=[(0, "No"), (1, "Yes")],
                db_column="Vancomycin Aministration (0 = no, 1 = yes)",
                default="No",
                max_length=1,
            ),
        ),
    ]
